Repository CMPUT301F23T06/SoftwareSolutionsSquad, pull requests merged in 2023-11, with the labels that each got.

#28 feat: 1.03.01 - Edit Items and refactor Add/Edit functionality
  app/src/main/java/com/example/softwaresolutionssquad/AddItemFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/InventoryItem.java
  app/src/main/java/com/example/softwaresolutionssquad/MainActivity.java
  app/src/main/res/layout/inventory_item_layout.xml
Labels: enhancement

#29 closes: 1.04.01 and 2.02.01 and 2.03.01
  app/src/main/java/com/example/softwaresolutionssquad/InventoryItem.java
  app/src/main/java/com/example/softwaresolutionssquad/InventoryListAdapter.java
  app/src/main/java/com/example/softwaresolutionssquad/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#31 Firestore is now connected to the app for add/edit/delete items using generated ID
  app/src/main/java/com/example/softwaresolutionssquad/AddItemFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/InventoryItem.java
  app/src/main/java/com/example/softwaresolutionssquad/InventoryListAdapter.java
  app/src/main/java/com/example/softwaresolutionssquad/MainActivity.java
Labels: enhancement

#33 refactor: password hashing and error handling
  app/src/main/java/com/example/softwaresolutionssquad/LoginActivity.java
  app/src/main/java/com/example/softwaresolutionssquad/SignupActivity.java
Labels: enhancement

#36 feat: 2.05.01, 2.06.01, 2.07.01 - Date, keyword, make filters on ItemList
  app/build.gradle.kts
  app/src/main/java/com/example/softwaresolutionssquad/AddItemFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#37 feat: 2.04.01 - Sort Task in ItemList
  app/src/main/java/com/example/softwaresolutionssquad/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#38 refactor: add more tests for login and sign up
  app/src/androidTest/java/com/example/softwaresolutionssquad/LoginTest.java
  app/src/androidTest/java/com/example/softwaresolutionssquad/SignupTest.java
  app/src/main/java/com/example/softwaresolutionssquad/LoginActivity.java
  app/src/main/java/com/example/softwaresolutionssquad/SignupActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
Labels: enhancement

#42 refactor: comment code and code cleanup
  app/src/androidTest/java/com/example/softwaresolutionssquad/LoginTest.java
  app/src/androidTest/java/com/example/softwaresolutionssquad/SignupTest.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/DatabaseController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/DateFilterController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/FilterController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/InventoryController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/KeywordFilterController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/MakeFilterController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/SortController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/TagController.java
  app/src/main/java/com/example/softwaresolutionssquad/controllers/Utils.java
  app/src/main/java/com/example/softwaresolutionssquad/models/ComparatorFactory.java
  app/src/main/java/com/example/softwaresolutionssquad/models/InventoryItem.java
  app/src/main/java/com/example/softwaresolutionssquad/models/InventoryModel.java
  app/src/main/java/com/example/softwaresolutionssquad/views/AddItemFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/views/InventoryListAdapter.java
  app/src/main/java/com/example/softwaresolutionssquad/views/LoginActivity.java
  app/src/main/java/com/example/softwaresolutionssquad/views/MainActivity.java
  app/src/main/java/com/example/softwaresolutionssquad/views/SignupActivity.java
Labels: documentation

#45 add: items intent testing implemented
  app/src/androidTest/java/com/example/softwaresolutionssquad/ItemTest.java
  app/src/androidTest/java/com/example/softwaresolutionssquad/LoginTest.java
Labels: enhancement

#47 tests: add unit tests to github actions
  .github/workflows/android.yml
Labels: enhancement

#43 feat: manage tags and slight refactor
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/softwaresolutionssquad/controllers/DatabaseController.java
  app/src/main/java/com/example/softwaresolutionssquad/views/AddItemFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/views/AddTagFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/views/HomeFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/views/LoginActivity.java
  app/src/main/java/com/example/softwaresolutionssquad/views/MainActivity.java
  app/src/main/java/com/example/softwaresolutionssquad/views/MyApp.java
  app/src/main/java/com/example/softwaresolutionssquad/views/ProfileFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/views/TagFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/views/TagListAdapter.java
  app/src/main/java/com/example/softwaresolutionssquad/views/UserViewModel.java
  app/src/main/res/color/nav_item.xml
  app/src/main/res/drawable/edit_text_outline.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/less_round_btn.xml
  app/src/main/res/drawable/nav_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_tag.xml
  app/src/main/res/layout/fragment_dummy.xml
  app/src/main/res/layout/fragment_home_layout.xml
  app/src/main/res/layout/fragment_tag_layout.xml
  app/src/main/res/layout/inventory_item_layout.xml
  app/src/main/res/layout/tag_list.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
Labels: enhancement

#50 feat: add item from camera roll for item
  app/build.gradle.kts
  app/src/androidTest/java/com/example/softwaresolutionssquad/ItemTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/softwaresolutionssquad/controllers/DateFilterController.java
  app/src/main/java/com/example/softwaresolutionssquad/models/InventoryItem.java
  app/src/main/java/com/example/softwaresolutionssquad/views/AddItemFragment.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_add_item.xml
  app/src/main/res/layout/fragment_view_item_photo.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/softwaresolutionssquad/ComparatorFactoryTest.java
  app/src/test/java/com/example/softwaresolutionssquad/InventoryItemTest.java
  app/src/test/java/com/example/softwaresolutionssquad/InventoryModelTest.java
  build.gradle.kts
Labels: enhancement, Final Checkpoint

#55 Update works properly again
  app/src/main/java/com/example/softwaresolutionssquad/views/AddItemNextFragment.java
Labels: bug

#60 User story 03.03.01 completed, can select and add tags
  app/src/androidTest/java/com/example/softwaresolutionssquad/ItemTest.java
  app/src/main/java/com/example/softwaresolutionssquad/views/HomeFragment.java
  app/src/main/java/com/example/softwaresolutionssquad/views/InventoryListAdapter.java
  app/src/main/res/layout/fragment_home_layout.xml
Labels: enhancement, Final Checkpoint
